name: Deploy

on:
  push:
    types: [master]

jobs:
  deploy:
    name: Deploy to datalake
    runs-on: ubuntu-lastest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9.0
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.0
    
      - name: HashiCorp - Setup Terraform
        Uses: hashicorp/setup-terraform@1.1.9

      - name: Configure AWS Credentials
        Uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: IaC Apply
        env:
          COMMAND_IAC: terraform
        run: |
          cd infrastructure
          $COMMAND_IAC init
          $COMMAND_IAC validate
          $COMMAND_IAC plan
          $COMMAND_IAC apply -auto-approve

